import type { DeckConfig } from "@aeon/types";

// Ported verbatim from Presentation_Platform.html (AEON_DECK, lines 512-854) — every
// service, price band, surcharge, discovery question, and static slide copy is an exact
// copy of the prototype's data, not a re-creation from the spec description.
export const amazonDspDeck: DeckConfig = {
  id: "aeon-logistics",
  industry: "Logistics & Last-Mile Delivery",
  companyName: "Amazon DSP",
  tagline: "Back-office and virtual operations for Amazon DSPs, AFPs, and FedEx ISPs.",
  logo: { type: "imagePair", srcLight: "/brand/aeon-synergies-light-bg.svg", srcDark: "/brand/aeon-synergies-dark-bg.svg" },
  secondaryLogo: { type: "imagePair", srcLight: "/brand/aeon-miles-light-bg.svg", srcDark: "/brand/aeon-miles-dark-bg.svg" },
  watermark: { type: "image", src: "/brand/aeon-icon.png" },
  colors: { amber: "#16A6CE", teal: "#0C7B82", ink: "#F1F5F5", panel: "#FFFFFF", panel2: "#E4EDEF", fog: "#5C6E73", paper: "#15282D" },
  pricingModels: [{ id: "primary", label: "Routes per day", unit: "routes", questionText: "How many routes do you run per day?", isPrimary: true }],
  services: [
    {
      id: "payroll",
      name: "Payroll Compliance Management",
      team: "Payroll & Compliance Team",
      tagline: "Accurate, timely payments",
      category: "major",
      pricingModelId: "primary",
      bandLabel: "Route-based · 5 bands",
      handle: [
        "Daily timecard review with missing-punch, duplicate-punch, and break validation",
        "Payroll validation, hours audit, and bonus/incentive calculations each cycle",
        "PTO tracking and approval support so nothing slips past a pay run",
        "Daily driver attendance monitoring — late arrivals, no-shows, call-outs, dress code",
        "Overtime validation to catch errors before they hit payroll",
        "Exception flagging so nothing reaches payroll unreviewed",
      ],
      stats: [
        { v: "↓ 80%", l: "Fewer payroll exceptions reaching sign-off" },
        { v: "100%", l: "Daily attendance logged & tracked" },
      ],
      dashboards: ["Payroll Summary", "Payroll Exception Report", "Compliance Dashboard", "Attendance Analytics"],
      priceBands: [
        { upTo: 15, price: 500 },
        { upTo: 25, price: 600 },
        { upTo: 35, price: 650 },
        { upTo: 50, price: 850 },
        { upTo: null, price: null },
      ],
      reportSlides: [
        {
          title: "Payroll vs Revenue, Week 25 (06/15/2025 to 06/21/2025)",
          template: {
            kind: "particulars-table",
            rows: [
              { label: "Pay Date", value: "06/27/2025", isCurrency: false },
              { label: "Total Gross Pay (Payroll)", value: "148,150.73" },
              { label: "Tax - Employer Contributions", value: "13,813.80" },
              { label: "Worker Comp Benefits", value: "8,390.60" },
              { label: "Employee Insurance", value: "29.00" },
              { label: "Employee 401k", value: "1,860.13" },
              { label: "Total Company Liability (Payroll)", value: "172,244.26", bold: true },
              { label: "Total Route Revenue", value: "161,351.00" },
              { label: "Profit/Loss (Revenue - Payroll)", value: "10,893.26", bold: true, highlight: "negative" },
            ],
          },
        },
        {
          title: "Overtime Analysis, Week 25 (06/15/2025 to 06/21/2025)",
          template: {
            kind: "particulars-table",
            valueColumnLabel: "Nos",
            rows: [
              { label: "No of OT Employees", value: "10.00", isCurrency: false },
              { label: "Employees more than 12hrs", value: "2.00", isCurrency: false },
            ],
            extraList: {
              heading: "List of Overtime Employees",
              items: [
                { label: "Brown, Tavianna", value: "11.35" },
                { label: "Kellam, Tahira", value: "12.30" },
                { label: "Samaniego, Joel", value: "12.15" },
                { label: "Watkins, Tyree", value: "10.35" },
                { label: "Sesay, Unisa", value: "10.26" },
                { label: "Souders, Jason", value: "11.04" },
              ],
            },
          },
        },
      ],
    },
    {
      id: "invoice",
      name: "Invoice Dispute Management",
      team: "Accounting & Finance Team",
      tagline: "Protect against revenue leakage",
      category: "strategic",
      pricingModelId: "primary",
      bandLabel: "Flat · 2 bands",
      handle: [
        "Weekly route invoice validation against block payments and bonuses",
        "Monthly vehicle, rental, fuel, and maintenance reimbursement validation",
        "Expense validation across insurance, workers' comp, fuel, and payroll vendors",
        "Billing discrepancy identification with full supporting documentation",
        "Dispute submission and follow-up with Amazon through resolution",
        "Revenue recovery reporting on every recovered dollar",
      ],
      stats: [
        { v: "↑ Recovery", l: "On every valid billing discrepancy found" },
        { v: "100%", l: "Disputes tracked to resolution" },
      ],
      dashboards: [
        "AFS vs. Fleet Capacity Comparison",
        "Revenue Recovery Dashboard",
        "Dispute Aging Report",
        "Recovery Trend Analysis",
      ],
      priceBands: [
        { upTo: 25, price: 350 },
        { upTo: null, price: 400 },
      ],
      promoNote: "Free Trial: 3 Months — Comparison & Analysis of Revenue vs Expense",
      reportSlides: [
        {
          title: "Route Invoice Validation, Week 25 (06/15/2025 to 06/21/2025)",
          template: {
            kind: "particulars-table",
            rows: [
              { label: "Route Revenue Expected", value: "85,154.00" },
              { label: "Route Revenue Received", value: "85,154.00" },
              { label: "Dispute Value", value: "0", bold: true, highlight: "neutral" },
            ],
          },
        },
        {
          title: "Vehicle Invoice Validation, Jan 2025",
          template: {
            kind: "particulars-table",
            rows: [
              { label: "Vehicle Rent and Lease Receivable", value: "56,000.00" },
              { label: "Amazon Payments", sectionHeader: true },
              { label: "Vehicle Prepaid Amount", value: "50,004.03" },
              { label: "Vehicle Reconciled Amount", value: "4,724.99" },
              { label: "Dispute Value", value: "1,270.98", bold: true, highlight: "negative" },
            ],
          },
        },
        {
          title: "Vehicle Rental Validation, Week 25 (06/15/2025 to 06/21/2025)",
          template: {
            kind: "particulars-table",
            rows: [
              { label: "Rental Paid", value: "6,300" },
              { label: "Rental Payable", value: "6,300" },
              { label: "Dispute Value", value: "0", bold: true, highlight: "neutral" },
            ],
          },
        },
      ],
    },
    {
      id: "compliance",
      name: "Driver Compliance Management",
      team: "Payroll & Compliance Team",
      tagline: "Audit-ready compliance, always",
      category: "strategic",
      pricingModelId: "primary",
      bandLabel: "Route-based · 3 bands",
      handle: [
        "FMLA leave tracking, eligibility coordination, and certification management",
        "OSHA recordkeeping and workplace injury documentation",
        "Workers' compensation claim filing, carrier coordination, and reconciliation",
        "Unemployment claim documentation and state agency response coordination",
        "Rejected and disputed claim assistance through appeal",
        "Amazon audit readiness — checklist management and document gap tracking",
      ],
      stats: [
        { v: "100%", l: "OSHA/FMLA documentation tracked" },
        { v: "↓ Exposure", l: "Faster claim response turnaround" },
      ],
      dashboards: [
        "Claim Status Reports",
        "Compliance & Audit Readiness Tracking",
        "WC Reconciliation & Reporting",
        "Corrective Action Tracking",
      ],
      priceBands: [
        { upTo: 20, price: 350 },
        { upTo: 35, price: 500 },
        { upTo: null, price: 650 },
      ],
      promoNote: "Free Trial: 30 Days",
      reportSlides: [
        {
          title: "Workers' Comp Claim Snapshot, Current Period",
          illustrative: true,
          template: {
            kind: "particulars-table",
            valueColumnLabel: "Number of Claims",
            rows: [
              { label: "Claims Filed", value: "3", isCurrency: false },
              { label: "Claims In Review", value: "2", isCurrency: false },
              { label: "Claims Resolved", value: "1", isCurrency: false },
              { label: "Total Active Claims", value: "2", isCurrency: false, bold: true, highlight: "neutral" },
            ],
          },
        },
        {
          title: "Worker Comp Validation, Week 25",
          template: {
            kind: "particulars-table",
            rows: [
              { label: "Drivers Worker Comp", value: "7,650.00" },
              { label: "Management Worker Comp", value: "1,300.00" },
              { label: "Worker Comp Payable", value: "10,856.00" },
              { label: "Dispute Value", value: "1,906.00", bold: true, highlight: "positive" },
            ],
          },
        },
        {
          title: "Unemployment Claims, Week 25 (06/15/2025 to 06/21/2025)",
          template: {
            kind: "particulars-table",
            valueColumnLabel: "Number of Claims",
            rows: [
              { label: "Claims Filed by Former Employees", value: "4", isCurrency: false },
              { label: "Claims Contested by Us", value: "3", isCurrency: false },
              { label: "Claims Still Pending Decision", value: "1", isCurrency: false },
              { label: "Claims Successfully Contested", value: "3", isCurrency: false, bold: true, highlight: "positive" },
            ],
          },
        },
      ],
    },
    {
      id: "bookkeeping",
      name: "Expert Bookkeeping",
      team: "Accounting & Finance Team",
      tagline: "Accurate, audit-ready records",
      category: "strategic",
      pricingModelId: "primary",
      bandLabel: "Flat · 2 bands",
      handle: [
        "Daily transaction categorization across bank and credit card accounts",
        "Vendor bill recording and customer payment posting",
        "Bank, credit card, and Amazon payment reconciliation",
        "Monthly book closing with accrual and prepaid adjustments",
        "Balance sheet and P&L review before books are closed",
        "Chart of accounts setup and ongoing maintenance",
      ],
      stats: [
        { v: "5 days", l: "Typical monthly close turnaround" },
        { v: "100%", l: "Transactions reconciled monthly" },
      ],
      dashboards: ["Profit & Loss", "Balance Sheet", "Cash Flow Statement", "Executive Financial Dashboard"],
      priceBands: [
        { upTo: 25, price: 300 },
        { upTo: null, price: 350 },
      ],
      reportSlides: [
        {
          title: "Profitability Metrics, Jan 2025",
          template: {
            kind: "particulars-table",
            showPctColumns: true,
            rows: [
              { label: "Total Revenue", suggestedPct: "100", actualPct: "100", value: "515,079.21" },
              { label: "Expenses", sectionHeader: true },
              { label: "Total Wages and Salaries", suggestedPct: "50", actualPct: "93.52", value: "481,704.96", highlight: "negative" },
              { label: "Worker's Comp Insurance", suggestedPct: "5", actualPct: "5.96", value: "30,695.66", highlight: "negative" },
              { label: "Total Vehicle Rental and Lease", suggestedPct: "10", actualPct: "9.35", value: "48,174.25", highlight: "positive" },
              { label: "Total Vehicle Insurance", suggestedPct: "5", actualPct: "9.26", value: "47,684.48", highlight: "negative" },
              { label: "Total Other Vehicle Exp (R&M)", suggestedPct: "5", actualPct: "3.26", value: "16,779.36", highlight: "positive" },
              { label: "Total Other Business Exp", suggestedPct: "15", actualPct: "6.41", value: "33,006.81", highlight: "positive" },
              { label: "Net Profit/Loss", suggestedPct: "10 - 12", actualPct: "-27.76", value: "-142,967.53", bold: true, highlight: "negative" },
            ],
          },
        },
      ],
    },
    {
      id: "recruitment",
      name: "Driver Recruitment Management",
      team: "Talent Acquisition Team",
      tagline: "Hire faster, hire smarter",
      category: "major",
      pricingModelId: "primary",
      bandLabel: "Route-based · 3 bands",
      handle: [
        "Job posting, resume screening, and candidate shortlisting",
        "Interview scheduling and candidate communication end-to-end",
        "Amazon onboarding coordination — drug testing, background checks, badge requests, driver account setup",
        "Offer letters, employment documents, I-9 and E-Verify support",
        "Hiring tracker maintenance so no candidate falls through the cracks",
        "Payroll enrollment handoff the moment a driver is hired",
      ],
      stats: [
        { v: "↓ 35%", l: "Faster time-to-hire on average" },
        { v: "100%", l: "Onboarding steps tracked to completion" },
      ],
      dashboards: ["Hiring Funnel", "Time to Hire", "Recruitment Dashboard", "Hiring Status Report"],
      priceBands: [
        { upTo: 15, price: 600 },
        { upTo: 25, price: 700 },
        { upTo: null, price: 950 },
      ],
      reportSlides: [
        {
          title: "Recruitment Tracking System",
          template: {
            kind: "operational-table",
            columns: ["Candidate Name", "Email Address", "Phone Number", "Current Status", "Onboarding Status", "BGV Status", "Drug Test Status"],
            rows: [
              ["Vandyke, Alvin", "Alvin.dglb@gmail.com", "+1 (321) 526-8233", "Onboarding", "In-Progress", "Not Started", "Not Started"],
              ["Francis, Julia", "Julia.dglb@gmail.com", "+1 (321) 526-8233", "Payroll Enroll", "On-boarded", "Completed", "Passed"],
              ["Smith, Isaiah", "Isaiah.dglb@gmail.com", "+1 (321) 526-8233", "Drug Test", "On-boarded", "Completed", "In-Progress"],
              ["Griffith, Ty Andrew", "Andrew.dglb@gmail.com", "+1 (321) 526-8233", "Training", "Off-boarded", "Completed", "Completed"],
              ["Johnson, Daniel Anthony", "Johnson.dglb@gmail.com", "+1 (321) 526-8233", "BGV", "Off-boarded", "Failed", "Not Started"],
            ],
          },
        },
        {
          title: "Recruitment Funnel Summary, This Period",
          template: {
            kind: "particulars-table",
            valueColumnLabel: "Count",
            rows: [
              { label: "Onboarded — Total onboarded", value: "88", isCurrency: false },
              { label: "BGV — Pending of 60", value: "15", isCurrency: false },
              { label: "Drug Test — Passed of 40", value: "26", isCurrency: false },
              { label: "Training — In progress", value: "19", isCurrency: false },
              { label: "Offboarded — This period", value: "12", isCurrency: false, bold: true, highlight: "negative" },
            ],
          },
        },
      ],
    },
    {
      id: "dispatch",
      name: "Virtual Dispatch Operator",
      team: "Virtual Assistance Team",
      tagline: "On-time performance, every day",
      category: "major",
      pricingModelId: "primary",
      bandLabel: "Route-based · 4 bands",
      handle: [
        "Pre-wave readiness — attendance verification, route assignment, vehicle allocation",
        "Live route monitoring from Wave Time through Return to Station",
        "Real-time driver assistance and delay/exception resolution",
        "Unscheduled break and violation monitoring with dispute management",
        "LSC case creation and station team coordination for operational issues",
        "RTS and returned-package tracking through close of day",
      ],
      stats: [
        { v: "↑ 12%", l: "On-time RTS completion" },
        { v: "Live", l: "Coverage from Wave Time to close of day" },
      ],
      dashboards: [
        "EOD Dispatch & Route Completion Summary",
        "RTS & Returned Package Report",
        "Operational Exception Summary",
        "EOD Operational Dashboard",
      ],
      priceBands: [
        { upTo: 15, price: 1300 },
        { upTo: 30, price: 1800 },
        { upTo: 50, price: 2200 },
        { upTo: null, price: null },
      ],
      surcharge: { questionId: "hoursOver12", amount: 200 },
      reportSlides: [
        {
          title: "End-of-Day Dispatch Summary, Week 25",
          illustrative: true,
          template: {
            kind: "particulars-table",
            rows: [
              { label: "Routes Dispatched", value: "22", isCurrency: false },
              { label: "Routes Completed On-Time", value: "20", isCurrency: false },
              { label: "RTS / Returned Packages", value: "14", isCurrency: false },
              { label: "On-Time Completion Rate", value: "91%", isCurrency: false, bold: true, highlight: "positive" },
            ],
          },
        },
        {
          title: "Dispatch Tracking, Week 25",
          template: {
            kind: "operational-table",
            columns: [
              "Van Details",
              "Delivery Associates",
              "Route Code",
              "Device No",
              "BP No",
              "Route Type",
              "Stops",
              "PSTD",
              "NSL",
              "MIS",
              "UTL",
              "BC",
              "RJD",
              "FDD",
              "UTA",
              "MP",
              "D",
              "OODT",
              "PD",
              "Fuel Level",
              "Mileage",
              "Pre-Trip DVIC",
              "Break 1",
              "Break 2",
              "Total Break",
              "Violation",
              "Post-Trip DVIC",
            ],
            rows: [
              [
                "4339", "Dwain Coleman Jr", "CX57", "4339", "11", "Standard Parcel Electric - Rivian MEDIUM", "170",
                "244", "", "1", "", "", "", "", "", "", "", "", "243", "", "67,043", "Completed", "", "", "", "", "Completed",
              ],
              [
                "2787", "Neciko Willams", "CX60", "2787", "44", "Standard Parcel Electric - Rivian MEDIUM", "174",
                "298", "", "", "", "", "", "", "", "", "1", "", "297", "", "26,224", "Completed", "30", "", "30", "", "Completed",
              ],
              [
                "8", "Kawan Clark Jr", "CX63", "8", "15", "Standard Parcel Step Van - US", "165",
                "240", "", "", "", "", "3", "", "2", "", "", "", "235", "1/2", "84,544", "Completed", "30", "", "30", "", "Completed",
              ],
              [
                "27", "Deon Thomas", "CX69", "4403", "37", "Standard Parcel Electric - Rivian MEDIUM", "172",
                "284", "", "2", "", "", "", "", "", "", "", "1", "283", "", "27,259", "Completed", "30", "", "30", "Speed violation", "Completed",
              ],
            ],
            summary: {
              label: "Planned vs. Executed",
              items: [
                { label: "Planned Stops (Target)", value: "700" },
                { label: "Stops Executed", value: "681", highlight: "negative" },
                { label: "Planned Routes", value: "4" },
                { label: "Routes Executed", value: "4", highlight: "positive" },
              ],
            },
          },
        },
      ],
    },
    {
      id: "performance",
      name: "Route Performance Management",
      team: "Virtual Assistance Team",
      tagline: "Protect your scorecard performance",
      category: "strategic",
      pricingModelId: "primary",
      bandLabel: "Route-based · 3 bands",
      handle: [
        "Weekly scorecard review and metric validation (CDF, DSB, DCR, PCB)",
        "Scorecard discrepancy identification and dispute submission",
        "Individual driver scorecard preparation with achievement and violation feedback",
        "Personalized coaching recommendations and corrective action tracking",
        "Performance gap identification before it becomes a compliance issue",
        "Weekly management performance summaries",
      ],
      stats: [
        { v: "↑ Scores", l: "CDF / DSB / DCR trend improvement via coaching" },
        { v: "100%", l: "Scorecards reviewed weekly" },
      ],
      dashboards: [
        "Performance Trends",
        "Scorecard Dispute Status Report",
        "Best/Poor Performer Analysis",
        "Weekly Management Performance Summary",
      ],
      priceBands: [
        { upTo: 20, price: 500 },
        { upTo: 35, price: 600 },
        { upTo: null, price: 800 },
      ],
      reportSlides: [
        {
          title: "CDF",
          template: {
            kind: "bar-highlights",
            chartTitle: "Incidents",
            items: [
              { label: "Delivered to Wrong Address", count: 30 },
              { label: "DA did not follow my delivery instructions", count: 28 },
              { label: "DA Mishandled Package", count: 4 },
              { label: "DA was Unprofessional", count: 4 },
              { label: "Received Wrong Item", count: 3 },
            ],
            sidebarLabel: "Top 3",
            summary: "69 total incidents across 46 drivers this week",
            colorVariant: "teal",
          },
        },
        {
          title: "DSB",
          template: {
            kind: "bar-highlights",
            chartTitle: "Incidents",
            items: [
              { label: "Incorrect Scan Usage - Attended Delivery", count: 6 },
              { label: "Delivered > 50 m", count: 2 },
              { label: "Scanned - Not Delivered - Not Returned", count: 2 },
              { label: "Simultaneous Deliveries", count: 1 },
            ],
            sidebarLabel: "Top Fields",
            summary: "11 total scorecard-impacting incidents across 7 drivers this week",
            colorVariant: "amber",
          },
        },
        {
          title: "Weekly Scorecard Snapshot",
          illustrative: true,
          template: {
            kind: "operational-table",
            columns: ["Driver", "CDF", "DSB", "DCR"],
            rows: [
              ["Brown, Tavianna", "1", "2", "98.2"],
              ["Kellam, Tahira", "2", "1", "96.5"],
              ["Samaniego, Joel", "3", "2", "94.1"],
            ],
          },
        },
      ],
    },
  ],
  team: [
    { initials: "BP", name: "Bharath Prasad", title: "Chief Executive Officer · Co-Founder", email: "bharathprasad@amazondsp.com", phone: "+1 (323) 426-7978" },
    { initials: "AH", name: "Abbie Joseph-Harrington", title: "Partner, Regional Head (US) · Former DSP Owner", email: "abbieJosephHarrington@amazondsp.com", phone: "+1 (951) 525-5745" },
    { initials: "RH", name: "Raghotham Harisha", title: "Chief Technical Officer (CTO) · Co-Founder", email: "raghotham.harisha@amazondsp.com", phone: "+1 (951) 525-5745" },
    { initials: "NA", name: "Nihal Alphons", title: "DSP Manager, Finance & Payroll · Co-Founder", email: "nihal.alphons@amazondsp.com", phone: "+1 (302) 305-2419" },
    { initials: "RD", name: "Roshan Dsouza", title: "DSP Manager, Recruitment & Dispatch · Co-Founder", email: "roshan.dsouza@amazondsp.com", phone: "+1 (302) 300-1147" },
  ],
  staticContent: {
    cover: {
      title1: "The Expert Team Behind",
      title2: "Amazon DSPs, AFPs & FedEx ISPs",
      sub: "Our expert operations team runs your back office so you can run the fleet.",
    },
    about: {
      eyebrow: "WHO WE ARE",
      title1: "One partner.",
      title2: "One expert team.",
      body: "Amazon DSP is a dedicated back-office and virtual operations team built specifically for the last-mile delivery ecosystem — purpose-built to support **Amazon DSPs**, **Amazon AFPs**, and **FedEx ISPs**.\n\nOne team, embedded in your daily operations across __payroll, hiring, dispatch, compliance, and finance__ — not a rotating cast of vendors.",
      bullets: [
        "A single contract and account relationship — no coordinating between separate vendors",
        "The same expert team learns your station once and carries that context across every service",
        "One escalation path — no \"that's the other team's issue\"",
      ],
      focusLabel: "INDUSTRIES WE SERVE",
      focusAreas: [
        { primary: "Amazon DSPs", secondary: "& AFPs" },
        { primary: "FedEx ISPs", secondary: "& Delivery Partners" },
        { primary: "Last-Mile", secondary: "Delivery" },
        { primary: "Fleet &", secondary: "Route Operations" },
      ],
    },
    how: {
      steps: [
        { t: "Understanding", d: "We learn your station, your routes, and how you currently handle payroll, hiring, dispatch, and disputes — and where it's costing you time or money today." },
        { t: "Implementation", d: "Our expert team is onboarded to your systems and SOPs, aligned to your reporting cadence, and live inside your operation — not a slow ramp-up." },
        { t: "Optimization", d: "Ongoing KPI tracking and process refinement — recovering more revenue, tightening compliance, and expanding coverage as your fleet grows." },
      ],
    },
    challenges: {
      items: [
        { title: "Thin Margins", description: "Thin margins under constant rate and cost pressure" },
        { title: "Driver Turnover", description: "High driver turnover with a recruiting pipeline that can't keep pace" },
        { title: "Payroll Errors", description: "Manual payroll and timecard errors creating compliance exposure" },
        { title: "Revenue Leakage", description: "Revenue quietly leaking through unvalidated invoices and missed disputes" },
        { title: "Scorecard Pressure", description: "Scorecard volatility and Amazon audit pressure with no dedicated owner" },
        { title: "Fragmented Data", description: "Fragmented spreadsheets instead of one source of operational truth" },
        { title: "Owner Time Drain", description: "Owners doing back-office work instead of growing the fleet" },
      ],
    },
    benefits: {
      items: [
        { title: "Dedicated Expert Team", description: "A dedicated expert team embedded in your operation — not a rotating help desk" },
        { title: "Recovered Revenue", description: "Recovered revenue through rigorous invoice and scorecard dispute management" },
        { title: "Reduced Compliance Risk", description: "Reduced compliance exposure across payroll, FMLA/OSHA, and workers' comp" },
        { title: "Faster Hiring", description: "A faster, cleaner hiring pipeline that keeps routes covered" },
        { title: "Real-Time Dispatch", description: "Real-time dispatch coverage without adding in-house headcount" },
        { title: "Transparent Reporting", description: "Transparent monthly KPI reporting across every function you outsource" },
        { title: "Predictable Pricing", description: "Predictable, route-based pricing that scales as your fleet grows" },
      ],
    },
    qa: {
      title: "Questions?",
      sub: "Let's talk about what running your back office on Aeon Miles would look like.",
      email: "info@amazondsp.com",
      phone: "+1 (302) 498-9899",
      web: "www.amazondsp.com",
      address: "800 N King St, Suite 304 #3725, Wilmington, DE 19801",
    },
  },
  discoveryQuestions: [
    { id: "dspName", section: "general", label: "DSP / business name", type: "text", placeholder: "e.g. Coleman Logistics LLC" },
    { id: "location", section: "general", label: "Which location is your DSP station in?", type: "text", placeholder: "e.g. DBK4 – Newark, NJ" },
    { id: "amzlAmxl", section: "general", label: "Are you a AMZL/AMXL?", type: "select", options: ["AMZL", "AMXL", "Both"] },
    { id: "tenure", section: "general", label: "How long have you been in the DSP business?", type: "text", placeholder: "e.g. 2.5 years" },
    { id: "wavesPerDay", section: "general", label: "How many waves per day?", type: "number", placeholder: "e.g. 3" },
    { id: "driverComms", section: "general", label: "What driver communication software do you use?", type: "text", placeholder: "e.g. WhatsApp, Slack, Detrack" },
    { id: "backOfficeModel", section: "general", label: "How are you currently managing the back-office operations?", type: "toggle", options: ["In-house", "Outsourced"] },
    { id: "currentProcess", section: "general", label: "Can you brief us the current process payroll, hiring, invoice disputes, and other operations?", type: "textarea" },
    { id: "painPoints", section: "general", label: "Can you share us your pain points?", type: "textarea" },

    { id: "payrollApp", section: "general", relatedService: "payroll", label: "What payroll application do you use?", type: "text", placeholder: "e.g. Gusto, ADP, QuickBooks Payroll" },
    { id: "payrollFrequency", section: "general", relatedService: "payroll", label: "What is your payroll frequency?", type: "toggle", options: ["Weekly", "Bi-Weekly"] },
    { id: "numDrivers", section: "general", relatedService: "payroll", label: "How many drivers do you currently have?", type: "number", placeholder: "e.g. 35" },

    { id: "bgvVendor", section: "general", relatedService: "recruitment", label: "Who is your vendor for BGV & Drug Test?", type: "text" },
    { id: "hiringRequirement", section: "general", relatedService: "recruitment", label: "What is your hiring requirement? (drivers to be fully hired per month/week)", type: "text", placeholder: "e.g. 5 per month" },
    { id: "offerLetterTiming", section: "general", relatedService: "recruitment", label: "Do you send the Offer Letter before Onboarding or before Training?", type: "select", options: ["Before Onboarding", "Before Training"] },
    { id: "marijuanaTesting", section: "general", relatedService: "recruitment", label: "Do you have Marijuana testing?", type: "toggle", options: ["No", "Yes"] },

    { id: "deliveryStartTime", section: "general", relatedService: "dispatch", label: "What is the start time of the day delivery?", type: "time" },
    { id: "deliveryEndTime", section: "general", relatedService: "dispatch", label: "What is the expected end time of the day delivery?", type: "time" },
    { id: "dspPerformanceScoreDispatch", section: "general", relatedService: "dispatch", label: "What is your current DSP Performance Score?", type: "select", options: ["Poor", "Good", "Great", "Fantastic", "Fantastic Plus"] },
    {
      id: "hoursOver12",
      section: "surcharge",
      relatedService: "dispatch",
      label: "What are your route hours?",
      type: "toggle",
      options: ["Up to 12 hrs/day", "More than 12 hrs/day"],
      surchargeFor: "dispatch",
      hint: "Adds a surcharge to Virtual Dispatch only, shown as one combined rate.",
    },
    {
      id: "over12DriverCount",
      section: "general",
      relatedService: "dispatch",
      label: "How many drivers regularly work the >12hr shifts?",
      type: "number",
      placeholder: "e.g. 8",
      dependsOn: { questionId: "hoursOver12", value: true },
    },

    { id: "vanCount", section: "general", relatedService: "invoice", label: "How many rental vans and branded vans do you have?", type: "text", placeholder: "e.g. 12 rental, 8 branded" },
    { id: "vehicleInsuranceVendor", section: "general", relatedService: "invoice", label: "Who is your Vehicle Insurance vendor?", type: "text" },

    { id: "claimsExpected", section: "general", relatedService: "compliance", label: "How many claims do you expect monthly?", type: "number", placeholder: "e.g. 2" },
    { id: "complianceAssist", section: "general", relatedService: "compliance", label: "Who is currently assisting drivers for their compliance?", type: "text" },

    { id: "dspPerformanceScorePerformance", section: "general", relatedService: "performance", label: "What is your current DSP Performance Score?", type: "select", options: ["Poor", "Good", "Great", "Fantastic", "Fantastic Plus"] },
    { id: "violationsTotal", section: "general", relatedService: "performance", label: "How many violations on average per day do you expect? (total)", type: "number", placeholder: "e.g. 2" },
    { id: "violationsCDF", section: "general", relatedService: "performance", label: "CDF violations (optional)", type: "number" },
    { id: "violationsDSB", section: "general", relatedService: "performance", label: "DSB violations (optional)", type: "number" },
    { id: "violationsDCR", section: "general", relatedService: "performance", label: "DCR violations (optional)", type: "number" },
    { id: "disputeHandler", section: "general", relatedService: "performance", label: "Who is handling the disputes?", type: "text" },
  ],
};
